spring.application.name=ALMACENMULTIPRO

server.port=9090

# ======================
# H2 DATABASE
# ======================

spring.datasource.url=jdbc:h2:mem:almacen;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# ======================
# H2 CONSOLE
# ======================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ======================
# SQL SCRIPTS
# ======================

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.encoding=UTF-8

# ======================
# JPA
# ======================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ======================
# HIKARI
# ======================

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1